# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: false
warnings_are_errors: false

before_install:
  - tlmgr install booktabs caption fancyhdr footmisc geometry numprint pdflscape ragged2e 